### ISSUE TITLE
建议把 effective python 也加入 LTS

### ISSUE THREAD

**Issue by wizardforcel** [xx-zh/xx-zh-roadmap#9]
[编写高质量代码改善 Python 程序的 91 个建议.zip](https://github.com/xx-zh/xx-zh-roadmap/files/5313815/Python.91.zip)

**Comment by gdut-yy** [comment]
gitbook: https://l1nwatch.gitbook.io/writing_solid_python_code_gitbook/
github: https://github.com/L1nwatch/writing_solid_python_code_gitbook
